MODEL:
  EXTRA:
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS:
    - '*'
    STAGE2:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      NUM_BRANCHES: 2
      NUM_CHANNELS:
      - 32
      - 64
      NUM_MODULES: 1
    STAGE3:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_BRANCHES: 3
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      NUM_MODULES: 1
    STAGE4:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_BRANCHES: 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      NUM_MODULES: 1
  INIT_WEIGHTS: true
  NUM_JOINTS: 13
